runtime: python37
service: default

handlers:
  - url: /
    secure: always
    static_files: public/index.html
    upload: public/index.html

  - url: /((.*\/)*[^\/]+\.[^\/]+)$
    secure: always
    static_files: public/\1
    upload: public/.*

  - url: /((.*\/)*[^\/]+\.[^\/]+)$
    secure: always
    static_files: public/\1
    upload: public/.*

  - url: /(.*?)/?$
    secure: always
    static_files: public/\1/index.html
    upload: public/.*/index.html
